name: build + publish

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Publish Docker Image
              uses: matootie/github-docker@v3.1.0
              with:
                  accessToken: ${{ github.token }}
                  containerRegistry: true

            - name: Deploy on CapRover
              uses: caprover/deploy-from-github@v1.1.2
              with:
                  server: '${{ secrets.SERVER_URL }}'
                  app: '${{ secrets.APP_NAME }}'
                  token: '${{ secrets.APP_TOKEN }}'
                  image: '${{ secrets.IMAGE_NAME }}'
